<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <RootNamespace>NetCore_Ethernet_Serial_Console_App</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Brainboxes.IO" Version="1.5.0.7" />
  </ItemGroup>

</Project>
