#!/usr/bin/env python3
"""
Post-processor for DocFxMarkdownGen output.

Augments the Docusaurus markdown generated by dfmg with YAML fields it skips:
- remarks: Inserted after the summary, before the Declaration code block
- example: Inserted after the member's last section (before the next heading)

Also cleans up HTML-escaped XML tags left in summaries by dfmg.

Pipeline: docfx metadata → dfmg → postprocess-dfmg.py → docusaurus

Usage:
    python postprocess-dfmg.py [--yaml-path api] [--md-path docusaurus/api]
"""

import argparse
import html
import os
import re
import sys

import yaml


def load_yaml_items(yaml_dir):
    """Load all items from DocFX YAML files, keyed by uid."""
    items = {}
    for filename in os.listdir(yaml_dir):
        if not filename.endswith(".yml"):
            continue
        filepath = os.path.join(yaml_dir, filename)
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
        # Remove YAML MIME header that PyYAML can't handle
        content = re.sub(r"^### YamlMime:\w+\n", "", content)
        try:
            data = yaml.safe_load(content)
        except yaml.YAMLError as e:
            print(f"Warning: Failed to parse {filename}: {e}", file=sys.stderr)
            continue
        if not data or "items" not in data:
            continue
        for item in data["items"]:
            uid = item.get("uid", "")
            if uid:
                items[uid] = item
    return items


def extract_remarks(item):
    """Extract remarks text from a YAML item."""
    remarks = item.get("remarks")
    if not remarks or not str(remarks).strip():
        return None
    return clean_docfx_html(str(remarks).strip())


def extract_examples(item):
    """Extract example content from a YAML item."""
    examples = item.get("example")
    if not examples or examples == []:
        return None
    # DocFX examples can be a list of strings or a list of dicts
    result = []
    if isinstance(examples, list):
        for ex in examples:
            if isinstance(ex, str) and ex.strip():
                result.append(ex.strip())
            elif isinstance(ex, dict):
                content = ex.get("content", "")
                if content and str(content).strip():
                    result.append(str(content).strip())
    elif isinstance(examples, str) and examples.strip():
        result.append(examples.strip())
    return result if result else None


def clean_docfx_html(text):
    """Clean up DocFX HTML artifacts in text."""
    # Convert <code class="paramref">name</code> to `name`
    text = re.sub(
        r'<code class="paramref">([^<]+)</code>', r"`\1`", text
    )
    # Convert <code>text</code> to `text`
    text = re.sub(r"<code>([^<]+)</code>", r"`\1`", text)
    # Convert <c>text</c> to `text`
    text = re.sub(r"<c>([^<]+)</c>", r"`\1`", text)
    # Convert <see cref="T:Namespace.Type"/> to `Type`
    text = re.sub(
        r'<see cref="[TFMPE]:([^"]+)"\s*/?>',
        lambda m: f"`{m.group(1).split('.')[-1]}`",
        text,
    )
    # Convert <xref href="..."> to link text
    text = re.sub(
        r'<xref href="[^"]*"[^>]*>([^<]*)</xref>', r"`\1`", text
    )
    # Convert <a href="url">text</a> to [text](url)
    text = re.sub(r'<a href="([^"]+)">([^<]+)</a>', r"[\2](\1)", text)
    # Convert <para> to newlines
    text = re.sub(r"<para>\s*", "\n\n", text)
    text = re.sub(r"\s*</para>", "\n", text)
    # Convert <list type="bullet"> items
    text = re.sub(r"<list[^>]*>", "", text)
    text = re.sub(r"</list>", "", text)
    text = re.sub(r"<item>\s*<term>([^<]+)</term>\s*<description>([^<]+)</description>\s*</item>",
                  r"- **\1**: \2", text)
    text = re.sub(r"<item>", "- ", text)
    text = re.sub(r"</item>", "", text)
    text = re.sub(r"<term>([^<]+)</term>", r"**\1**", text)
    text = re.sub(r"<description>([^<]+)</description>", r"\1", text)
    # Clean remaining tags
    text = re.sub(r"</?b>", "**", text)
    text = re.sub(r"<br\s*/?>", "\n", text)
    # Unescape HTML entities
    text = html.unescape(text)
    return text.strip()


def format_remarks_section(remarks_text):
    """Format remarks as a markdown section."""
    return f"\n##### Remarks\n\n{remarks_text}\n"


def format_examples_section(examples):
    """Format examples as a markdown section with code blocks."""
    parts = ["\n##### Examples\n"]
    for example in examples:
        # If the example doesn't already have code fences, wrap it
        if "```" not in example:
            parts.append(f"\n```csharp\n{example}\n```\n")
        else:
            parts.append(f"\n{example}\n")
    return "\n".join(parts)


def clean_escaped_example_tags(content):
    """Remove HTML-escaped <example> tags from summary text and convert to code blocks."""
    # Pattern: &lt;example&gt; ... &lt;/example&gt;
    def replace_escaped_example(match):
        code = match.group(1).strip()
        return f"\n\n##### Examples\n\n```csharp\n{code}\n```\n"

    content = re.sub(
        r"&lt;example&gt;\s*(.*?)\s*&lt;/example&gt;",
        replace_escaped_example,
        content,
        flags=re.DOTALL,
    )
    return content


def find_class_name_from_md(content):
    """Extract the class/interface/enum name from markdown content."""
    m = re.match(r"^# (?:Class|Interface|Enum|Delegate|Struct)\s+(\S+)", content, re.MULTILINE)
    return m.group(1) if m else None


def get_namespace_from_path(md_path):
    """Derive namespace from the markdown file path structure."""
    # docs/docusaurus/api/Brainboxes.IO/EDDevice.md → Brainboxes.IO
    parts = md_path.replace("\\", "/").split("/")
    # Find the namespace directory (parent of the .md file)
    for i, part in enumerate(parts):
        if part.endswith(".md"):
            if i > 0:
                return parts[i - 1]
    return ""


def build_name_to_uid_map(items, namespace):
    """Build a mapping from DFMG heading names to YAML UIDs for a given namespace."""
    mapping = {}
    for uid, item in items.items():
        if not uid.startswith(namespace + "."):
            continue
        name = item.get("name", "")
        item_type = item.get("type", "")
        if name:
            mapping[name] = uid
            # Also map without namespace prefix for nested lookups
            short_name = uid.split(".")[-1] if "." in uid else uid
            if short_name != name:
                mapping[short_name] = uid
    return mapping


def process_markdown_file(md_path, items):
    """Process a single markdown file, injecting remarks and examples."""
    with open(md_path, "r", encoding="utf-8") as f:
        content = f.read()

    original_content = content

    # Step 1: Clean up HTML-escaped example tags in summaries
    content = clean_escaped_example_tags(content)

    # Step 2: Determine namespace and class from path/content
    namespace = get_namespace_from_path(md_path)
    class_name = find_class_name_from_md(content)

    if not namespace or not class_name:
        # Might be an index file or namespace doc
        if content != original_content:
            with open(md_path, "w", encoding="utf-8") as f:
                f.write(content)
        return content != original_content

    class_uid = f"{namespace}.{class_name}"

    # Step 3: Inject class-level remarks and examples
    class_item = items.get(class_uid)
    if class_item:
        remarks = extract_remarks(class_item)
        examples = extract_examples(class_item)

        if remarks or examples:
            inject_text = ""
            if remarks:
                inject_text += format_remarks_section(remarks)
            if examples:
                inject_text += format_examples_section(examples)

            # Insert before "###### **Assembly**:" line
            assembly_pattern = r"(###### \*\*Assembly\*\*:)"
            if re.search(assembly_pattern, content):
                content = re.sub(
                    assembly_pattern,
                    inject_text + r"\n\1",
                    content,
                    count=1,
                )

    # Step 4: Inject member-level remarks and examples
    # Find all ### headings (members) and their positions
    member_headings = list(re.finditer(r"^### (.+)$", content, re.MULTILINE))

    # Process in reverse order so insertions don't shift positions
    for i in range(len(member_headings) - 1, -1, -1):
        heading_match = member_headings[i]
        heading_name = heading_match.group(1).strip()

        # Find the end of this member's content (next ### or ## or EOF)
        start = heading_match.end()
        if i < len(member_headings) - 1:
            end = member_headings[i + 1].start()
        else:
            # Check for next ## heading
            next_section = re.search(r"^## ", content[start:], re.MULTILINE)
            end = start + next_section.start() if next_section else len(content)

        member_content = content[start:end]

        # Try to find matching YAML item
        member_uid = None
        for uid, item in items.items():
            if not uid.startswith(class_uid + "."):
                continue
            item_name = item.get("name", "")
            if item_name == heading_name:
                member_uid = uid
                break

        if not member_uid:
            continue

        member_item = items[member_uid]
        remarks = extract_remarks(member_item)
        examples = extract_examples(member_item)

        if not remarks and not examples:
            continue

        # Build injection text
        inject_text = ""
        if remarks:
            inject_text += format_remarks_section(remarks)
        if examples:
            inject_text += format_examples_section(examples)

        # Find insertion point: after summary, before ```csharp title="Declaration"
        decl_match = re.search(r'```csharp title="Declaration"', member_content)
        if decl_match:
            insert_pos = start + decl_match.start()
            content = content[:insert_pos] + inject_text + "\n" + content[insert_pos:]
        else:
            # No declaration block found; insert at end of member
            content = content[:end] + inject_text + "\n" + content[end:]

    # Step 5: Write if changed
    if content != original_content:
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(content)
        return True
    return False


def main():
    parser = argparse.ArgumentParser(
        description="Post-process DocFxMarkdownGen output to add remarks and examples"
    )
    parser.add_argument(
        "--yaml-path",
        default="api",
        help="Path to DocFX YAML files (default: api)",
    )
    parser.add_argument(
        "--md-path",
        default="docusaurus/api",
        help="Path to generated markdown files (default: docusaurus/api)",
    )
    args = parser.parse_args()

    # Resolve paths relative to script directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    yaml_dir = os.path.join(script_dir, args.yaml_path)
    md_dir = os.path.join(script_dir, args.md_path)

    if not os.path.isdir(yaml_dir):
        print(f"Error: YAML directory not found: {yaml_dir}", file=sys.stderr)
        sys.exit(1)
    if not os.path.isdir(md_dir):
        print(f"Error: Markdown directory not found: {md_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"Loading YAML from: {yaml_dir}")
    items = load_yaml_items(yaml_dir)
    print(f"Loaded {len(items)} items from YAML")

    modified_count = 0
    for root, dirs, files in os.walk(md_dir):
        for filename in files:
            if not filename.endswith(".md"):
                continue
            md_path = os.path.join(root, filename)
            if process_markdown_file(md_path, items):
                modified_count += 1
                print(f"  Modified: {os.path.relpath(md_path, md_dir)}")

    print(f"Post-processing complete: {modified_count} files modified")


if __name__ == "__main__":
    main()
